[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$v3CXNNBf$62yIxIJljzZ4F/PCDGT8A."
  ]

[http.routers.api]
  rule = "Host(`monitor.febf.mywire.org`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
